spring:
  data:
    mongodb:
<<<<<<< HEAD
      database: bookmarkservice
=======
  jackson:
    serialization:
      fail-on-empty-beans: false
  config:
    import: optional:application-secret.yml

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb: DEBUG
    org.springframework.mail: DEBUG
    com.bookmarkservice.common.email: DEBUG
    root: INFO
