spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: bookmark.service.noreply@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  config:
    import: optional:application-secret.yml
